export default[
  {
    "_id":"001",
    "name": "大鱼1",
    "ename":"Big fish",
    "type": "爱情",
    "area": "北美",
    "time": "90分钟",
    "poster": "",
    "upDate": "2012-02-20",
    "score": 9.2,
    "count": "15亿",
    "intro": "哈哈哈哈哈"
  },
  {
    "_id":"002",
    "name": "大鱼2",
    "ename":"Big fish",
    "type": "爱情",
    "area": "北美",
    "time": "90分钟",
    "poster": "",
    "upDate": "2012-02-20",
    "score": 9.2,
    "count": "15亿",
    "intro": "哈哈哈哈哈"
  },
  {
    "_id":"003",
    "name": "大鱼3",
    "ename":"Big fish",
    "type": "爱情",
    "area": "北美",
    "time": "90分钟",
    "poster": "",
    "upDate": "2012-02-20",
    "score": 9.2,
    "count": "15亿",
    "intro": "哈哈哈哈哈"
  },
  {
    "_id":"004",
    "name": "大鱼4",
    "ename":"Big fish",
    "type": "爱情",
    "area": "北美",
    "time": "90分钟",
    "poster": "",
    "upDate": "2012-02-20",
    "score": 9.2,
    "count": "15亿",
    "intro": "哈哈哈哈哈"
  },
  {
    "_id":"005",
    "name": "大鱼5",
    "ename":"Big fish",
    "type": "爱情",
    "area": "北美",
    "time": "90分钟",
    "poster": "",
    "upDate": "2012-02-20",
    "score": 9.2,
    "count": "15亿",
    "intro": "哈哈哈哈哈"
  },
  {
    "_id":"006",
    "name": "大鱼6",
    "ename":"Big fish",
    "type": "爱情",
    "area": "北美",
    "time": "90分钟",
    "poster": "",
    "upDate": "2012-02-20",
    "score": 9.2,
    "count": "15亿",
    "intro": "哈哈哈哈哈"
  },
  {
    "_id":"007",
    "name": "大鱼7",
    "ename":"Big fish",
    "type": "爱情",
    "area": "北美",
    "time": "90分钟",
    "poster": "",
    "upDate": "2012-02-20",
    "score": 9.2,
    "count": "15亿",
    "intro": "哈哈哈哈哈"
  },
  {
    "_id":"008",
    "name": "大鱼8",
    "ename":"Big fish",
    "type": "爱情",
    "area": "北美",
    "time": "90分钟",
    "poster": "",
    "upDate": "2012-02-20",
    "score": 9.2,
    "count": "15亿",
    "intro": "哈哈哈哈哈"
  },
  {
    "_id":"009",
    "name": "大鱼9",
    "ename":"Big fish",
    "type": "爱情",
    "area": "北美",
    "time": "90分钟",
    "poster": "",
    "upDate": "2012-02-20",
    "score": 9.2,
    "count": "15亿",
    "intro": "哈哈哈哈哈"
  },
  {
    "_id":"010",
    "name": "大鱼10",
    "ename":"Big fish",
    "type": "爱情",
    "area": "北美",
    "time": "90分钟",
    "poster": "",
    "upDate": "2012-02-20",
    "score": 9.2,
    "count": "15亿",
    "intro": "哈哈哈哈哈"
  },
]